feat(script): update scripts from ceur

diff --git a/bin/check-index-errors b/bin/check-index-errors
--- a/bin/check-index-errors
+++ b/bin/check-index-errors
@@ -14,7 +14,7 @@
 #
 # Call this script in the directory that contains the index.html file that you want to check.
 #
-# Manfred 2020-03-20 (2025-07-02)
+# Manfred 2020-03-20 (2025-09-22)
 #
 
 if [ ! -f index.html ]; then
@@ -47,10 +47,10 @@ then echo " ";
      echo "String 'OPub' found in index.html";
 fi
 
-if grep -q "Coeditor," index.html;
+if grep -q -E "Coeditor|Carlos Nombre|Anne Foé" index.html;
 then echo " ";
      echo " ==========> ERROR (A3) in index.html!!!!";
-     echo "String 'Coeditor' found in the footer of index.html";
+     echo "String 'Coeditor' or 'Carlos Nombre' or 'Anne Foé' left over from template Vol-XXX found in index.html";
 fi
 
 if grep -q "<li>" index.html;
@@ -174,6 +174,7 @@ do
   then 
     echo " ==========> ERROR (A18) in index.html!!!!";
     echo "The label $KEYWORD must have at least one value in index.html. It your case, the value is $NRWORDS."
+    echo " ";
   fi
 done
 
@@ -183,6 +184,7 @@ if [[ $? != 0 ]];
 then echo " ";
      echo " ==========> ERROR (A19) in index.html!!!!";
      echo "The validator link at the end of index.html must initially include the parameter 'Vol-XXX'. Otherwise, our scripts cannot insert the right volume number here!";
+     echo " ";
 fi
 
 
@@ -197,7 +199,8 @@ if grep CEURAUTHOR index.html | grep -q " and";
 then echo " ";
      echo " ==========> ERROR (A21) in index.html!!!!";
      echo "index.html contains CEURAUTHOR elements using 'and' as separator instead ','.";
-       grep -n -P 'CEURAUTHOR.*</span>, and' index.html
+     grep -n -P 'CEURAUTHOR.*</span>, and' index.html;
+     echo " ";
 fi
 
 # extract certain CEUR fields from the index.html file
@@ -219,7 +222,7 @@ then echo " ";
      echo $DUPPDFS
 fi
 
-DUPTITLES=`grep "CEURTITLE" index.html | sed "s/<a href/\\n<a href/g" | sed 's/\"/\"><\/a>\n/2' | grep href | sort | uniq --count | grep -v "1 <a"`
+DUPTITLES=`grep "CEURTITLE" index.html | sed "s/<a href/\\n<a href/g" | sed 's/\"/\"><\/a>\n/2' | grep href | sort | uniq --count | grep -Ev "^[[:space:]]*1 "`
 if [ "$DUPTITLES" != "" ]
 then echo " ";
      echo " ==========> ERROR (A24) in index.html!!!!";
@@ -270,22 +273,23 @@ then echo " ";
      echo "The index.html file must contain the tag <body> without any parameters.";
 fi
 
+
 ALLPDFSLINKED="yes"
 for f in *.pdf
 do
   # All PDF files must be linked in index.html
-  grep -q "$f" index.html
+  grep -q ""$f"" index.html
   if [[ $? != 0 ]];
   then
-    ALLPDFSLINKED="unlinkedpdffound"
-    echo "PDF file $f is not linked in index.html"
+    ALLPDFSLINKED="unlinkedpdffound";
+    echo "PDF file $f is not linked in index.html";
   fi
 done
 
 if [[ $ALLPDFSLINKED == "unlinkedpdffound" ]] ; then
   echo " ==========> ERROR (A30) in index.html!!!!";
-  echo "Make sure all paper PDFs are linked in index.html"
-  echo " "
+  echo "Make sure all paper PDFs are linked in index.html";
+  echo " ";
 fi
 
 
@@ -302,10 +306,52 @@ done
 
 if [[ $ALLPDFSEXISTS == "no" ]] ; then
   echo " ==========> ERROR (A31) in index.html!!!!";
-  echo "Make sure all refernces to paper PDFs in index.html also exist as file in the same directory"
+  echo "Make sure all references to paper PDFs in index.html also exist as file in the same directory"
   echo " "
 fi
 
+
+# A PDF file should be referenced only once in index.html
+DUPCOUNTRESULT=`grep -o '"[[:alnum:]_-]\+\.pdf"' index.html | sed 's/<[^>]*>//g' | tr -s '[:space:]' '\n' | grep -v '^$' | sort | uniq -c | awk '$1 > 1'`
+if [[ "$DUPCOUNTRESULT" != "" ]];
+then echo " ";
+     echo " ==========> ERROR (A32) in index.html!!!!";
+     echo "The index.html file has multiple references to the same PDF file.";
+fi
+
+if grep -q "<script" index.html;
+then echo " ";
+     echo " ==========> ERROR (A33) in index.html!!!!";
+     echo "Script keyword found in index.html; we do not allow JavaScript on our pages";
+fi
+
+if grep -q "http://" index.html;
+then echo " ";
+     echo " ==========> ERROR (A34) in index.html!!!!";
+     echo "Change occurrences of 'http://' to 'https://' since http is being phased out";
+fi
+
+if grep -q "0000-0000-0000-0000" index.html;
+then echo " ";
+     echo " ==========> ERROR (A35) in index.html!!!!";
+     echo "The index.html file has a dummy ORCID 0000-0000-0000-0000. Either correct or remove the tags itemcope itemtype and itemid";
+fi
+
+grep -q  "0074-XXX-C" index.html
+if [[ $? != 0 ]];
+then echo " ";
+     echo " ==========> ERROR (A36) in index.html!!!!";
+     echo "Do not change the URN template from Vol-XXX in the submission index.html file; we shall assign the URN automatically";
+     echo " ";
+fi
+
+grep -q  "\"CEURVOLNR\">Vol-XXX" index.html
+if [[ $? != 0 ]];
+then echo " ";
+     echo " ==========> ERROR (A37) in index.html!!!!";
+     echo "Do not change the volume number Vol-XXX in the submission index.html file; we shall assign it automatically";
+     echo " ";
+fi
 
 
 
diff --git a/bin/check-pdf-errors b/bin/check-pdf-errors
--- a/bin/check-pdf-errors
+++ b/bin/check-pdf-errors
@@ -10,14 +10,17 @@
 # The BASH script is part of the scripts used for CEUR-WS.org. No warrantee whatsoever. No support.
 #
 # Requires the installation of certain packages, in particular pdf2txt and pdffonts. The tool pdf2txt is part of the
-# package python-pdfminer. The pdffonts command is paper of the packacge poppler-utils.
+# package python-pdfminer.  The pdffonts command is paper of the package poppler-utils.
+# Install on Debian-based systems with
+#   sudo apt install python3-pdfminer
+#   sudo apt-get install poppler-utils
 #
 # Note that this script is updated on a regular basis, in particular to cover changes with
 # the CEURART layout for papers. See ceur-ws.org/Vol-XXX/ for the CEURART specification.
 #
 # Call this script in the directory that contains the PDF files that you want to check.
 #
-# Manfred 2024-08-17 (2025-06-14)
+# Manfred 2024-08-17 (2025-09-19)
 #
 
 ### Find pdf2txt implementation
@@ -54,7 +57,7 @@ do
   ${PDF2TXT} -m 2 "$f" | grep -E 'Abstract|Copyright' 2>&1 > /dev/null
   if [[ $? != 0 ]];
   then
-     if [[ "$f" != *"reface"*".pdf" && "$f" != *"rganization.pdf" && "$f" != *"ponsors.pdf" && "$f" != *"ommittee"*".pdf" ]]
+     if [[ "$f" != *"reface"*".pdf" && "$f" != *"rganization.pdf" && "$f" != *"ponsors.pdf" && "$f" != *"ommittee"*".pdf" && "$f" != *"matter"*".pdf" ]]
      then
         ABSTRACTWORD="notfound"
         echo "PDF file $f seems to have no readable text included but only binary data"
@@ -62,7 +65,7 @@ do
   fi
 done
 if [[ "$ABSTRACTWORD" == "notfound" ]] ; then
-  echo " ===> Make sure that paper PDFs have readable/selectable text in them; use a proper PDF printer driver on Windows or use LibreOffice PDF export"
+  echo " ===> Make sure that paper PDFs have readable/selectable text in them; use a proper PDF printer driver on Windows such as PDFCreator or use LibreOffice PDF export"
   echo " "
 else
   echo "ok"
@@ -81,7 +84,7 @@ do
   ${PDF2TXT} -m 2 "$f" | grep -E 'Creative.*Commons.*License|Commons.*License.*Attribution' | grep -Ev '2022|2023' 2>&1 > /dev/null
   if [[ $? != 0 ]];
   then
-     if [[ "$f" != *"reface"*".pdf" && "$f" != *"rganization.pdf" && "$f" != *"ponsors.pdf" && "$f" != *"ommittee"*".pdf" ]]
+     if [[ "$f" != *"reface"*".pdf" && "$f" != *"rganization.pdf" && "$f" != *"ponsors.pdf" && "$f" != *"ommittee"*".pdf" && "$f" != *"matter"*".pdf" ]]
      then
         CREATIVECOMMONS="notfound"
         echo "PDF file $f seems to lack the proper copyright clause or copyright year on page 1"
@@ -99,21 +102,43 @@ fi
 
 
 echo "(*) Declaration on Generative AI"
-GENAIDECL="found"
+GENAIDECL="ok"
 for f in *.pdf
 do
-  # PDF files should have the string "Creative Commons License" on the first two pages
-  ${PDF2TXT} "$f" | grep -E 'Declaration on Generative AI' 2>&1 > /dev/null
+  # front or backmatter files are not tested
+  if [[ "$f" == *"reface"*".pdf" || "$f" == *"rganization.pdf" || "$f" == *"ponsors.pdf" || "$f" == *"bstract"*".pdf"  || "$f" == *"ommittee"*".pdf" || "$f" == *"matter"*".pdf" ]]
+  then
+     continue
+  fi
+
+  temp_file=$(mktemp /tmp/pdftext.XXXXXX.txt)
+#  pdftotext "$f" "$temp_file"
+  ${PDF2TXT} "$f" > "$temp_file"
+  # Test 1: PDF files should have a section "Declaration on Generative AI"
+  cat "$temp_file" | grep -E 'Declaration .. [G|g]enerative AI' 2>&1 > /dev/null
   if [[ $? != 0 ]];
   then
-     if [[ "$f" != *"reface"*".pdf" && "$f" != *"rganization.pdf" &&"$f" != *"ponsors.pdf" && "$f" != *"bstract"*".pdf"  && "$f" != *"ommittee"*".pdf" ]]
-     then
-        GENAIDECL="notfound"
-        echo "PDF file $f seems to lack a statement Declaration on Generative AI"
-     fi
+     GENAIDECL="notok"
+     echo "PDF file $f seems to lack a section Declaration on Generative AI"
+     continue;
   fi
+  # Test 2: The phrase "The author ... not employed any Generative AI tools." is fine; not more checks needed
+  cat "$temp_file" | grep -E 'The author.*not employed any Generative AI tools\.' 2>&1 > /dev/null
+  if [[ $? == 0 ]];
+  then
+    continue;  # This file is ok
+  fi
+  # If Test2 failed then Test 3 is required: The GenAI statement must contain the phrase "reviewed|*full responsibility"
+  # Not yet happy with this solution. We want authors to follow our template but some make slight variations. Others big ones.
+  # cat "$temp_file" | tr '\n' ' ' | grep -E 'reviewed|full responsibility' 2>&1 > /dev/null
+  #  if [[ $? != 0 ]];
+  #then
+  #   GENAIDECL="notok"
+  #   echo "PDF file $f seems to use a non-standard text for the Declaration on Generative AI"
+  #fi
+  /bin/rm "$temp_file"
 done
-if [[ $GENAIDECL == "notfound" ]] ; then
+if [[ $GENAIDECL == "notok" ]] ; then
   echo " ===> Make sure that paper PDFs have a Generative AI Declaration conforming https://ceur-ws.org/GenAI/Policy.html"
   echo " "
 else
@@ -121,21 +146,22 @@ else
   echo " "
 fi
 
+
 echo ""
-echo "(*) Use of CEUR-WS.org logo or link before watermarking"
+echo "(*) Use of CEUR-WS.org logo or link or string CEUR Workshop Proceedings before publication"
 CEURWSLINKFOUND="notfound"
 for f in *.pdf
 do
   # PDF files should not have the string "(CEUR-WS.org)" on the first two pages
-  ${PDF2TXT} -m 2 "$f" | grep '(CEUR-WS.org)' 2>&1 > /dev/null
+  ${PDF2TXT} -m 2 "$f" | grep -E '(CEUR-WS.org)|CEUR Workshop Proceedings' 2>&1 > /dev/null
   if [[ $? == 0 ]];
   then
      CEURWSLINKFOUND="found"
-     echo "PDF file $f has an old footnote with 'CEUR-WS.org' on it before watermarking or uses the string (CEUR-WS.org)"
+     echo "PDF file $f uses 'CEUR-WS.org' or 'CEUR Workshop Proceedings' before publication"
   fi
 done
 if [[ $CEURWSLINKFOUND == "found" ]] ; then
-  echo " ===> Use the latest CEURART template from https://ceur-ws.org/Vol-XXX/, which does not have a footnote with the CEUR-WS logo"
+  echo " ===> Use the latest CEURART template from https://ceur-ws.org/Vol-XXX/, which does not have a footnote with the CEUR-WS logo; Do not use the string 'CEUR Workshop Proceedings' in the header or footer of papers"
   echo " "
 else
   echo "ok"
@@ -185,4 +211,25 @@ else
   echo "ok"
   echo " "
 
+fi
+
+echo ""
+echo "(*) Leftover elements from CEURART in the footer of page 1"
+NOLEFTOVER="yes"
+for f in *.pdf
+do
+  # PDF files should not have leftover elements from the CEURART template in the footer
+  ${PDF2TXT} -m 2 "$f" | grep -E '0000-0000-0000-0000|Woodstock.*22|0000-0002-0877-7063.*0000-0001-7116-9338.*0000-0002-9421-8566'  2>&1 > /dev/null
+  if [[ $? == 0 ]];
+  then
+     NOLEFTOVER="no"
+     echo "PDF file $f seems to have some leftover elements from the footer of the CEURART template on page 1 such as ORCIDs or the event name"
+  fi
+done
+if [[ $NOLEFTOVER == "no" ]] ; then
+  echo " ===> Make sure that paper PDFs have correct data in the footnote section of page 1"
+  echo " "
+else
+  echo "ok"
+  echo " "
 fi
